In [42]:
import pandas as pd
train=pd.read_csv('/content/train.csv')
test=pd.read_csv('/content/test.csv')
train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [43]:
test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [44]:
df=pd.concat([train,test],sort=False)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,NaN,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,NaN,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,NaN,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,NaN,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,NaN,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [45]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1309 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     891 non-null    float64
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   object
 4   Sex          1309 non-null   object
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Cabin        295 non-null    object
 11  Embarked     1307 non-null   object
dtypes: float64(3), int64(4), object(5)
memory usage: 132.9+ KB

In [47]:
df.isnull().sum()

PassengerId       0
Survived        418
Pclass            0
Name              0
Sex               0
Age             263
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          2
dtype: int64

In [48]:
df=df.drop('Cabin',axis=1)

In [49]:
from sklearn.impute import SimpleImputer

print(f'The number of null values before the imputation is: {df.Age.isnull().sum()}')

imputer = SimpleImputer(strategy='mean')
df['Age'] = imputer.fit_transform(df[['Age']]).ravel()

print(f'The number of null values after the imputation is: {df.Age.isnull().sum()}')

The number of null values before the imputation is: 263
The number of null values after the imputation is: 0

In [50]:
df['Survived'] = imputer.fit_transform(df[['Survived']])

In [51]:
sii = SimpleImputer(strategy='most_frequent')

df['Embarked'] = sii.fit_transform(df[['Embarked']]).ravel()
df['Fare'] = sii.fit_transform(df[['Fare']]).ravel()

In [52]:
df=df.drop(['Name','Ticket'],axis=1)

In [53]:
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0.000000,3,male,22.000000,1,0,7.2500,S
1,2,1.000000,1,female,38.000000,1,0,71.2833,C
2,3,1.000000,3,female,26.000000,0,0,7.9250,S
3,4,1.000000,1,female,35.000000,1,0,53.1000,S
4,5,0.000000,3,male,35.000000,0,0,8.0500,S
...,...,...,...,...,...,...,...,...,...
413,1305,0.383838,3,male,29.881138,0,0,8.0500,S
414,1306,0.383838,1,female,39.000000,0,0,108.9000,C
415,1307,0.383838,3,male,38.500000,0,0,7.2500,S
416,1308,0.383838,3,male,29.881138,0,0,8.0500,S
417,1309,0.383838,3,male,29.881138,1,1,22.3583,C

In [54]:
threshold=3
from scipy.stats import zscore
numerical_features=['Fare','Age']
z_scores=np.abs(zscore(df[numerical_features]))
print(z_scores)

[[0.5031762  0.61197171]
 [0.73480864 0.63043107]
 [0.49012612 0.30137101]
 ...
 [0.5031762  0.66925616]
 [0.48770944 0.        ]
 [0.21108058 0.        ]]

In [65]:
outliers=np.where(z_scores>threshold)
print(outliers)

(array([  27,   88,   96,  116,  118,  258,  299,  311,  341,  377,  380,
        438,  493,  527,  557,  630,  672,  679,  689,  700,  716,  730,
        737,  742,  745,  779,  851,  915,  944,  950,  955,  960,  965,
        966,  972,  987, 1005, 1033, 1047, 1075, 1093, 1109, 1215, 1234,
       1266, 1298]), array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0]))

In [64]:
from scipy.stats.mstats import winsorize
df['Age'] = winsorize(df['Age'], limits=[0.15, 0.15]).data
df['Fare'] = winsorize(df['Fare'], limits=[0.15, 0.15]).data

In [66]:
# Remove outliers
df_no_outliers = df[(np.abs(zscore(df[numerical_features])) < threshold).all(axis=1)]

print(f"Shape of the DataFrame before removing outliers: {df.shape}")
print(f"Shape of the DataFrame after removing outliers: {df_no_outliers.shape}")

Shape of the DataFrame before removing outliers: (1309, 9)
Shape of the DataFrame after removing outliers: (1309, 9)

In [69]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
df['Sex']=oe.fit_transform(df[['Sex']])
df['Embarked']=oe.fit_transform(df[['Embarked']])
df['Survived']=oe.fit_transform(df[['Survived']])
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0.0,3,1.0,22.000000,1,0,7.7500,2.0
1,2,2.0,1,0.0,38.000000,1,0,56.9292,0.0
2,3,2.0,3,0.0,26.000000,0,0,7.9250,2.0
3,4,2.0,1,0.0,35.000000,1,0,53.1000,2.0
4,5,0.0,3,1.0,35.000000,0,0,8.0500,2.0
...,...,...,...,...,...,...,...,...,...
413,1305,1.0,3,1.0,29.881138,0,0,8.0500,2.0
414,1306,1.0,1,0.0,39.000000,0,0,56.9292,0.0
415,1307,1.0,3,1.0,38.500000,0,0,7.7500,2.0
416,1308,1.0,3,1.0,29.881138,0,0,8.0500,2.0
417,1309,1.0,3,1.0,29.881138,1,1,22.3583,0.0

In [70]:
X=df.drop(['Survived'],axis=1)
y=df['Survived']

In [77]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
from sklearn.ensemble import AdaBoostClassifier
ab=AdaBoostClassifier(n_estimators=45,random_state=42,learning_rate=1)
ab.fit(X_train,y_train)
y_pred=ab.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8282442748091603